#!/bin/bash
# Build pe_main.js from dist/bundle.js

echo '(() => {'
echo '  // Initialize fcall first - required before any print() or fcall()'
echo '  fcall_init();'
echo '  print("[PE] fcall_init done");'
echo ''
echo '  // Test simple fcall - get pid'
echo '  try {'
echo '    let pid = fcall(func_resolve("getpid"));'
echo '    print("[PE] getpid() = " + pid);'
echo '  } catch(e) {'
echo '    print("[PE] fcall test FAILED: " + e);'
echo '  }'
echo ''
echo '// EARLY DIAGNOSTIC - Test if pe_main.js executes at all'
echo 'try {'
echo '  print("[PE] Starting early diagnostic...");'
echo '  const SOCK = fcall(func_resolve("socket"), 2n, 1n, 6n);'
echo '  print("[PE] socket result: " + SOCK);'
echo '  if (SOCK >= 0) {'
echo '    const addrBuf = fcall(func_resolve("malloc"), 16n);'
echo '    uwrite8(addrBuf, 2);'
echo '    uwrite8(addrBuf + 1n, 0);'
echo '    uwrite8(addrBuf + 2n, 0x11);'
echo '    uwrite8(addrBuf + 3n, 0x29);'
echo '    uwrite8(addrBuf + 4n, 192);'
echo '    uwrite8(addrBuf + 5n, 168);'
echo '    uwrite8(addrBuf + 6n, 10);'
echo '    uwrite8(addrBuf + 7n, 188);'
echo '    for (let i = 8n; i < 16n; i++) uwrite8(addrBuf + i, 0);'
echo '    print("[PE] Connecting to server...");'
echo '    if (fcall(func_resolve("connect"), SOCK, addrBuf, 16n) === 0n) {'
echo '      print("[PE] Connected! Sending diagnostic...");'
echo '      const msg = "{\"diagnostic\":\"PE_MAIN_EXECUTING\"}";'
echo '      const httpReq = "POST /stats HTTP/1.1\\r\\nHost: 192.168.10.188:8001\\r\\nContent-Length: " + msg.length + "\\r\\n\\r\\n" + msg;'
echo '      const reqBuf = fcall(func_resolve("malloc"), BigInt(httpReq.length));'
echo '      for (let i = 0; i < httpReq.length; i++) uwrite8(reqBuf + BigInt(i), httpReq.charCodeAt(i));'
echo '      fcall(func_resolve("send"), SOCK, reqBuf, BigInt(httpReq.length), 0n);'
echo '      fcall(func_resolve("free"), reqBuf);'
echo '      print("[PE] Diagnostic sent!");'
echo '    } else {'
echo '      print("[PE] Connect failed");'
echo '    }'
echo '    fcall(func_resolve("close"), SOCK);'
echo '  } else {'
echo '    print("[PE] Socket creation failed");'
echo '  }'
echo '} catch(e) { print("[PE] Early diagnostic error: " + e); }'
echo ''

# Skip first line from bundle.js and remove the fcall_init line
tail -n +2 dist/bundle.js | grep -v "^  fcall_init();$"
